name: jacoco_coverage

on:
  push:
    branches: [ "isw2" ]
  pull_request:
    branches: [ "isw2" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 8
        uses: actions/setup-java@v4
        with:
          java-version: '8'
          distribution: 'temurin'

      # to speed up next builds
      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Verify
        run: mvn verify

      - name: Build and test with JaCoCo
        run: mvn clean test -P jacoco

      - name: Upload JaCoCo report
        uses: actions/upload-artifact@v4
        with:
          name: jacoco-report
          path: bookkeeper-server/target/site/jacoco
          if-no-files-found: error
