name: jacoco_coverage

on:
  push:
    branches: [ "isw2" ]
  pull_request:
    branches: [ "isw2" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build
        run: mvn clean test -P jacoco

      - name: Upload report
        uses: actions/upload-artifact@v3
        with:
          name: jacoco-report
          path: bookkeeper-server/target/site/jacoco
          if-no-files-found: error
